### ISSUE TITLE
not able to run heartbeats

### ISSUE THREAD

**Issue by chen116** [libheartbeats/heartbeats#3]
Hi, 

I am trying to run some provided example after compiling, but I encountered such error:

 ./bin/tp: error while loading shared libraries: libhb-shared.so: cannot open shared object file: No such file or directory

any suggestion will help, thank you!

Victor

**Comment by connorimes** [comment]
Did you run `sudo make install`?  If so, you may also need to run `sudo ldconfig` to refresh the linker's cache.  If not, you need to update the `LD_LIBRARY_PATH` environment variable to include the location of compiled libraries.  For example, run `export LD_LIBRARY_PATH=$(pwd)/lib:$LD_LIBRARY_PATH` from the heartbeats base directory, then run `./bin/tp`

**Comment by chen116** [comment]
Hi,
Thank you for your response. It works now, thank!
Victor
